# This is a basic workflow to help you get started with Actions

name: build_ubuntu

# Triggered on push/pr against master.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # @todo -alternatively run on a docker container which already has dependencies installed.
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cuda: [10.1.105]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Investigate apt caching? https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow
    - name: install apt dependencies
      run: |
       echo "OS: ${{ matrix.os }}"
       echo "CUDA: ${{ matrix.cuda }}"



    - name: configure
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: compile
      run: |
        cd build
        make
    - name: execute
      run: |
        cd build
        ./main


