name: build_windows

# Triggered on push/pr against master.
on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

jobs:
  build:
    # @todo -alternatively run on a docker container which already has dependencies installed.
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        cuda: [10.2.89]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: get_os
      run: |
        echo "${{ matrix.os }}"
        echo "${{ matrix.cuda }}"


    - name: install_cuda
      run: |
        .\scripts\install_cuda_windows.ps1
        
        echo "::set-env name=CUDA_PATH::$env:CUDA_PATH"
        echo "::add-path::$env:CUDA_PATH/bin"
      shell: powershell

    - name: check_paths
      run: | 
        echo $PATH
        echo $CUDA_PATH
      shell: bash

    - name: temp_path_additions
      run: |
        echo "::set-env name=CUDA_PATH::/C/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2"
        echo "::add-path::/C/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.2/bin"

    - name: check_paths_again
      run: | 
        echo $PATH
        echo $CUDA_PATH
      shell: bash

    # - name: test_nvcc
    #   run: |
    #     echo $PATH
    #     nvcc -V
    #   shell: bash
