name: build_windows

# Triggered on push/pr against master.
on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

jobs:
  build:
    # @todo -alternatively run on a docker container which already has dependencies installed.
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        cuda: [10.2.89]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: get_os
      run: |
        echo "${{ matrix.os }}"
        echo "${{ matrix.cuda }}"


    - name: install_cuda
      run: .\scripts\install_cuda_windows.ps1
      shell: powershell

    - name: test_nvcc
      run: |
        nvcc -V
