# This is a basic workflow to help you get started with Actions

name: build_ubuntu

# Triggered on push/pr against master.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # @todo -alternatively run on a docker container which already has dependencies installed.
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cuda: [10.1.105]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Split version strings and set as environment variables for later use.
    - name: split_version
      run: |
        echo "::set-env name=CUDA_MAJOR::$(echo "${{ matrix.cuda }}" | cut -d. -f1)"
        echo "::set-env name=CUDA_MINOR::$(echo "${{ matrix.cuda }}" | cut -d. -f2)"
        echo "::set-env name=CUDA_PATCH::$(echo "${{ matrix.cuda }}" | cut -d. -f3)"
        echo "::set-env name=UBUNTU_VERSION::$(echo "${{ matrix.os }}" | tr -d '.\-')"

    # Investigate apt caching? https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow
    # @todo - would this be better in a script?
    - name: install cuda
      run: |
        sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget python3-pip doxygen
        CUDA_REPO_PKG=cuda-repo-${UBUNTU_VERSION}_${CUDA_MAJOR}.${CUDA_MINOR}.${CUDA_PATCH}-1_amd64.deb
        sudo wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
        sudo apt-key add 7fa2af80.pub
        wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${CUDA_REPO_PKG}
        sudo dpkg -i ${CUDA_REPO_PKG}
        rm ${CUDA_REPO_PKG}
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends cuda-compiler-${CUDA_MAJOR}-${CUDA_MINOR} cuda-cudart-dev-${CUDA_MAJOR}-${CUDA_MINOR} cuda-curand-dev-${CUDA_MAJOR}-${CUDA_MINOR} cuda-nvrtc-dev-${CUDA_MAJOR}-${CUDA_MINOR}
        CUDA_ROOT=/usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}
        echo "::set-env name=CUDA_ROOT::${CUDA_ROOT}"
        echo "::set-env name=PATH::${CUDA_ROOT}/bin:${PATH}"
        echo "::set-env name=LD_LIBRARY_PATH::${CUDA_ROOT}/lib:${LD_LIBRARY_PATH}"

    - name: install cpplint
      run: |
        pip3 install cpplint
        echo "::set-env name=PATH::$HOME/.local/bin:${PATH}"

    - name: version_check
      run: |
        echo $PATH
        nvcc --version
        which nvcc
        cpplint --version
        which cpplint
        cmake --version
        which cmake

    - name: configure
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: compile
      run: |
        cd build
        make
    # Disabled - cannot execute on github-hosted actions.
    # - name: execute
    #   run: |
    #     cd build
    #     ./main


