name: build_windows

on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2016]
        cuda: [9.0.176, 10.2.89]
        include:
          - os: windows-2019
            visual_studio: 2019
          - os: windows-2016
            visual_studio: 2017
    env:
      cuda: ${{ matrix.cuda }} 
      cuda_packages: "nvcc;visual_studio_integration;curand_dev;nvrtc_dev;"
      visual_studio: {{ matrix.visual_studio }}

    steps:

    - uses: actions/checkout@v2

    - name: Select Visual Studio
      run: |
        if()
      shell: powershell

    - name: Install CUDA
      run: |
        # Install CUDA via a powershell script
        .\scripts\install_cuda_windows.ps1
        # Abort if the script returned an error code
        if (!$?) { exit 1 }
        # Set paths for subsequent steps, using $env:CUDA_PATH
        echo "::set-env name=CUDA_PATH::$env:CUDA_PATH"
        echo "::add-path::$env:CUDA_PATH/bin"
      shell: powershell

    - name: Check Paths
      run: | 
        echo $PATH
        echo $CUDA_PATH
      shell: bash
    
    - name: Test NVCC
      run: |
        nvcc -V
      shell: bash


    # - name: install cpplint
    #   run: |
    #     pip3 install cpplint
    #     # echo "::add-path::$HOME/.local/bin:${PATH}"

    # - name: version_check
    #   run: |
    #     nvcc --version
    #     which nvcc
    #     cpplint --version
    #     which cpplint
    #     cmake --version
    #     which cmake

    # - name: configure
    #   run: |
    #     mkdir -p build
    #     cd build
    #     cmake .. -G "Visual Studio 15 2017" -A x64
    #     cmake .. -G "Visual Studio 16 2019" -A x64


    # - name: compile
    #   run: |
    #     make -j 2
    #   working-directory: build