# Ubuntu 16.04 supports CUDA 8.0+
name: Ubuntu1604

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        cuda: ["8.0", "9.0", "10.0", "11.0"]
    env:
      cuda: ${{ matrix.cuda }}

    steps:
    - uses: actions/checkout@v2

    - name: Install CUDA
      run: |
        source ./scripts/install_cuda_ubuntu.sh
        if [[ $? -eq 0 ]]; then
          echo "Settings Paths"
          echo "CUDA_PATH=${CUDA_PATH}"
          # Set paths for subsequent steps, using ${CUDA_PATH}
          echo "::set-env name=CUDA_PATH::${CUDA_PATH}"
          echo "::add-path::${CUDA_PATH}/bin"
          echo "::set-env name=LD_LIBRARY_PATH::${CUDA_PATH}/lib:${LD_LIBRARY_PATH}"
        fi
      shell: bash

    - name: Install cpplint
      run: |
        pip3 install cpplint
        echo "::add-path::$HOME/.local/bin"

    - name: Configure cmake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build . --target all --verbose -j 2
      working-directory: build

    # No GPU so no point in running
    # - name: Run
    #   run: ./main
    #   working-directory: build


