# Compile project on Ubuntu
name: Ubuntu

on:
  push:
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/Ubuntu.yml"
  # pull_request:
  #   paths:
  #     - "**"
  #     - "!.github"
  #     - ".github/workflows/Ubuntu.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          # 18.04 supports CUDA 10.1+ (gxx <= 8)
          - os: ubuntu-18.04
            cuda: "11.0"
            gcc: 8
            experimental: false
          - os: ubuntu-18.04
            cuda: "10.2"
            gcc: 8
            experimental: false
          - os: ubuntu-18.04
            cuda: "10.1"
            gcc: 8
            experimental: false

          # 16.04 supports CUDA 8+
          - os: ubuntu-16.04
            cuda: "11.0"
            gcc: 7
            experimental: false
          - os: ubuntu-16.04
            cuda: "10.2"
            gcc: 7
            experimental: false
          - os: ubuntu-16.04
            cuda: "10.1"
            gcc: 7
            experimental: false
          - os: ubuntu-16.04
            cuda: "10.0"
            gcc: 7
            experimental: false
          - os: ubuntu-16.04
            cuda: "9.2"
            gcc: 7
            experimental: false
          - os: ubuntu-16.04
            cuda: "9.1"
            gcc: 6
            experimental: false
          - os: ubuntu-16.04
            cuda: "9.0"
            gcc: 6
            experimental: false
          - os: ubuntu-16.04
            cuda: "8.0"
            gcc: 6
            experimental: true
    env:
      build_dir: "build"
      config: "Release"

    steps:
    - uses: actions/checkout@v2

    - name: Install CUDA
      env:
        cuda: ${{ matrix.cuda }}
      run: |
        source ./scripts/actions/install_cuda_ubuntu.sh
        if [[ $? -eq 0 ]]; then
          # Set paths for subsequent steps, using ${CUDA_PATH}
          echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
          echo "::set-env name=CUDA_PATH::${CUDA_PATH}"
          echo "::add-path::${CUDA_PATH}/bin"
          echo "::set-env name=LD_LIBRARY_PATH::${CUDA_PATH}/lib:${LD_LIBRARY_PATH}"
        fi
      shell: bash

    # Specify the correct host compilers
    - name: Install/Select gcc and g++ 
      run: |
        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
        echo "::set-env name=CC::/usr/bin/gcc-${{ matrix.gcc }}"
        echo "::set-env name=CXX::/usr/bin/g++-${{ matrix.gcc }}"
        echo "::set-env name=CUDAHOSTCXX::/usr/bin/g++-${{ matrix.gcc }}"

    - name: Configure cmake
      id: configure
      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      working-directory: ${{ env.build_dir }}
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi



    - name: Build everything else
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --target all --verbose -j `nproc`

