name: WindowsVisualStudio2017

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:  windows-2016
    strategy:
      fail-fast: false
      matrix:
        # cuda: [9.0.176, 10.0.130]
        cuda: [10.0.130]

    env:
      visual_studio: "Visual Studio 15 2017"
      cuda: ${{ matrix.cuda }} 

    steps:

    - uses: actions/checkout@v2

    - name: Install CUDA
      run: |
        # Install CUDA via a powershell script
        .\scripts\install_cuda_windows.ps1
        # Abort if the script returned an error code
        if (!$?) { exit 1 }
        # Set paths for subsequent steps, using $env:CUDA_PATH
        echo "::set-env name=CUDA_PATH::$env:CUDA_PATH"
        echo "::set-env name=CUDA_PATH_V10_0::$env:CUDA_PATH"
        echo "::add-path::$env:CUDA_PATH/bin"
      shell: powershell

    - name: Install cpplint
      run: |
        python -m pip install --upgrade cpplint

    - name: nvcc -V
      run: |
        echo $PATH
        echo $CUDA_PATH
        nvcc -V
      shell: bash

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -G "${{ env.visual_studio }}" -A x64
        cat 
      shell: bash


    - name: Build
      run: |
        make -j 2
      working-directory: build