name: windows_vs2017

on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

jobs:
  build:
    runs-on:  windows-2016
    strategy:
      fail-fast: false
      matrix:
        # Multiple cuda versions
        cuda: [9.0.176, 10.0.130, 10.2.89]

    env:
      cuda: ${{ matrix.cuda }} 
      visual_studio: "Visual Studio 15 2017"

    steps:

    - uses: actions/checkout@v2

    - name: Install CUDA
      run: |
        # Install CUDA via a powershell script
        .\scripts\install_cuda_windows.ps1
        # Abort if the script returned an error code
        if (!$?) { exit 1 }
        # Set paths for subsequent steps, using $env:CUDA_PATH
        echo "::set-env name=CUDA_PATH::$env:CUDA_PATH"
        echo "::add-path::$env:CUDA_PATH/bin"
      shell: powershell

    - name: install cpplint
      run: |
        python -m pip install --upgrade cpplint

    - name: version_check
      run: |
        nvcc --version
        which nvcc
        cpplint --version
        which cpplint
        cmake --version
        which cmake

    - name: configure
      run: |
        mkdir -p build
        cd build
        cmake .. -G "${{ env.visual_studio }}" -A x64


    # - name: compile
    #   run: |
    #     make -j 2
    #   working-directory: build